[package]
name = "reg-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.32.0"
reg-lang-compiler = { path = "../reg-lang-compiler" }
reg-lang-parser = { path = "../reg-lang-parser" }